### ISSUE TITLE
Pas de connexion via SSL

### ISSUE THREAD

**Issue by Zell40** [Tailszefox/LoupsGarous#1]
Bonjour,
Je viens d'installer votre robot sur mon serveur IRC InspircdV3 et lorsque je le lance via SSL, il ne se connecte pas et ne m'affiche pas d'erreur.
Si je le lance sans SSL, il se connecte correctement.
Je remarque que cela fait plusieurs années qu'il est en ligne sans que personne n'interviennent dessus donc j'imagine qu'il n'est peut être plus à jour pour InspircdV3 ?

Merci pour votre réponse.
Jessie

**Comment by Tailszefox** [comment]
Hello. Je dois dire, je suis assez surpris de voir de l'activité sur ce vieux projet, d'autant plus qu'il n'est pas compatible avec Python 3, vous avez dû avoir du mal à l'installer sur un système récent.

(Je suis aussi assez étonné de voir qu'il y a des gens qui utilisent encore IRC, je pensais que tout le monde était passé sur Discord.)

Effectivement, le support du SSL n'était pas présent parce que le seul serveur sur lequel j'ai utilisé le bot (à l'époque où je m'en servais encore) n'était pas configuré pour. La version de la librairie IRC utilisée par le bot ne supportait pas le SSL de toute façon.

J'ai trouvé une (vieille) version de cette librairie qui supporte le SSL mais qui reste compatible avec Python 2, j'ai donc fait les modifs appropriées pour que le bot puisse s'en servir. Il vous faudra désinstaller l'ancienne version de la librairie et installer la nouvelle (voir l'adresse dans setup/check_irclib.py) et préciser dans le fichier de configuration d'activer le SSL (voir prefs.example.ini).

J'ai fait un test rapide et j'ai réussi à faire une petite partie, mais je ne garantis pas que le bot marchera sur le long terme ou sur un autre serveur. S'il y a un souci, n'hésitez pas à répondre ou ouvrir un autre rapport de bug, mais là non plus je ne peux pas garantir que je puisse résoudre d'autres problèmes. Pour être honnête ça a déjà été assez compliqué de résoudre celui-ci, en grande partie à cause de l'âge du bot et de son support de Python 2 uniquement.

D'ailleurs, je déconseille d'utiliser Python 2 de manière générale vu qu'il n'est plus supporté depuis 4 ans. Il est toujours possible qu'il y ait des failles de sécurité dans le code du bot. Si vous voulez quand même l'utiliser, je conseille de le faire dans un environnement isolé comme une VM ou un container Docker. Mais après, à vous de voir !
